- name: Assert join command is available
  assert:
    that:
      - hostvars[groups['k8s_cp'][0]].k8s_join_command is defined
      - hostvars[groups['k8s_cp'][0]].k8s_join_command | length > 0
    fail_msg: "k8s_join_command not found in fact cache. Re-run CP caching task."

- name: Set join_cmd var
  set_fact:
    join_cmd: "{{ hostvars[groups['k8s_cp'][0]].k8s_join_command }}"

- name: Join node to cluster (idempotent)
  command: "{{ join_cmd }} --v=5"
  args:
    creates: /etc/kubernetes/kubelet.conf
