---
- name: kubeadm config (CP)
  copy:
    dest: /root/kubeadm-config.yaml
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      kubernetesVersion: {{ kubeadm_kubernetes_version }}
      networking:
        podSubnet: "{{ pod_cidr }}"
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      nodeRegistration:
        criSocket: "unix:///run/containerd/containerd.sock"

- name: kubeadm init
  command: kubeadm init --config=/root/kubeadm-config.yaml
  args: { creates: /etc/kubernetes/admin.conf }

- name: admin kubeconfig for root
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chown root:root /root/.kube/config
  changed_when: false

- name: Install Calico
  environment: { KUBECONFIG: /etc/kubernetes/admin.conf }
  command: kubectl apply -f {{ calico_manifest }}

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_cmd
  changed_when: false

- name: Write join command to bastion
  delegate_to: localhost
  run_once: true
  copy:
    dest: /tmp/k8s_join.sh
    mode: "0700"
    content: "{{ join_cmd.stdout | trim }}"
