---
- hosts: localhost
  gather_facts: false
  vars:
    bastion_user: "azureuser"
    kube_repo_channel: "v1.30"
    kubectl_pkg_version: "1.30.4-1.1"
    kubeconfig_content: "{{ hostvars[groups['k8s_cp'][0]].k8s_admin_kubeconfig }}"
    kube_home: "/home/{{ bastion_user }}/.kube"
  pre_tasks:
    - name: Assert kubeconfig is present in fact cache
      assert:
        that:
          - kubeconfig_content is defined
          - kubeconfig_content | length > 0
        fail_msg: >
          Cached kubeconfig not found. Re-run the CP task that sets
          'k8s_admin_kubeconfig' with cacheable: true.
  roles:
    - bastion_kubectl

