---
- hosts: localhost
  gather_facts: false
  vars:
    kube_repo_channel: "v1.30"          # pin channel if you like
    kubectl_pkg_version: "1.30.4-1.1"   # or omit to get latest in that channel
    kubeconfig_content: "{{ hostvars[groups['k8s_cp'][0]].k8s_admin_kubeconfig }}"
    kubeconfig_dest_dir: "{{ ansible_env.HOME + '/.kube' }}"
  pre_tasks:
    - name: Assert kubeconfig is present in fact cache
      assert:
        that:
          - kubeconfig_content is defined
          - kubeconfig_content | length > 0
        fail_msg: >
          Cached kubeconfig not found. Re-run the CP task that sets
          'k8s_admin_kubeconfig' with cacheable: true.
  roles:
    - bastion_kubectl

