- hosts: k8s_cp
  become: true
  gather_facts: false
  tasks:
    - name: Read admin.conf (base64)
      slurp:
        src: /etc/kubernetes/admin.conf
      register: adminconf
  
    - name: Write admin.conf to local file
      delegate_to: localhost
      run_once: true
      copy:
        dest: /home/azureuser/admin.conf
        mode: '0600'
        content: "{{ adminconf.content | b64decode }}"

    - name: Print kubeconfig to stdout (copy & store in your vault)
      delegate_to: localhost
      run_once: true
      vars:
        decoded: "{{ adminconf.content | b64decode }}"
      debug:
        msg: |
          ===== BEGIN KUBECONFIG admin.conf =====
          {{ decoded }}
          ===== END KUBECONFIG admin.conf =====
